### ISSUE TITLE
Version 1.1.0 does not have an image available

### ISSUE THREAD

**Issue by mdarocha** [QuinnMatthews/azureCommunicationServicesSMTPForwarder#4]
It seams like the [Docker build jobs](https://github.com/QuinnMatthews/azureCommunicationServicesSMTPForwarder/actions/workflows/docker-publish.yml) are not running.

**Comment by QuinnMatthews** [comment]
The nightly runs are going again, but I'm unsure how to tag them with the V1.1.0 tag...

**Comment by mdarocha** [comment]
You can probably do it manually, by using a combination of `docker pull`, `docker tag` and `docker push`. Or use [skopeo](https://github.com/containers/skopeo)

**Comment by QuinnMatthews** [comment]
This has been resolved. New builds will be done when releases are created.
